### ISSUE TITLE
Pocketbase

### ISSUE THREAD

**Issue by pastelcode** [denoland/wanted_modules#56]
https://github.com/pocketbase/pocketbase

**Comment by klerpi** [comment]
```ts
import PocketBase from "https://esm.sh/pocketbase@0.10.0";

const pb = PocketBase("pocketbaseurl.com");
```

Results in:
```
Watcher Process started.
error: Uncaught TypeError: Cannot set properties of undefined (setting 'cancelControllers')
    at s (https://esm.sh/v102/pocketbase@0.10.0/deno/pocketbase.js:2:34177)
    at file:///<redacted>/pockettest/main.ts:3:12
Watcher Process finished. Restarting on file change...
```

So a Deno module would be really cool for full typing support.

**Comment by klerpi** [comment]
> ```ts
> import PocketBase from "https://esm.sh/pocketbase@0.10.0";
> 
> const pb = PocketBase("pocketbaseurl.com");
> ```
> 
> Results in:
> 
> ```
> Watcher Process started.
> error: Uncaught TypeError: Cannot set properties of undefined (setting 'cancelControllers')
>     at s (https://esm.sh/v102/pocketbase@0.10.0/deno/pocketbase.js:2:34177)
>     at file:///<redacted>/pockettest/main.ts:3:12
> Watcher Process finished. Restarting on file change...
> ```
> 
> So a Deno module would be really cool for full typing support.

I don't know what changed exactly but it works now! Maybe I was doing something wrong.
